version: '3'

services: 
  server:
    build: 
      context: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis
    environment:
      - "PYTHONUNBUFFERED=1"

  redis:
    image: redis:latest
